<?php
// ============================================
// NOVA SETTINGS WRITER
// ============================================
// Helper function to rewrite nova/conf/nova_config_values.php
// Used by Super Admin Settings Page
//
// Created: November 2025
// Philosophy: Simple file writer with automatic backup
// ============================================

/**
 * Save settings to nova/conf/nova_config_values.php
 *
 * This function:
 * 1. Creates automatic timestamped backup of existing file (optional)
 * 2. Generates PHP array content with var_export()
 * 3. Writes new config values file
 * 4. Sets proper file permissions (0644)
 *
 * @param array $settings Associative array of settings
 * @param string $admin_email Email of admin making changes (for audit)
 * @param bool $create_backup Whether to create backup before saving (default: true)
 * @return array ['success' => bool, 'backup' => string|null, 'error' => string|null]
 */
function nova_save_config_values($settings, $admin_email = 'unknown', $create_backup = true)
{
  // ============================================
  // 1. DEFINE FILE PATH
  // ============================================
  $file_path = __DIR__ . '/../conf/nova_config_values.php';

  // ============================================
  // 2. CREATE BACKUP (if file exists and backup requested)
  // ============================================
  $backup_path = null;

  if ($create_backup && file_exists($file_path)) {
    $backup_path = $file_path . '.backup_' . date('Y-m-d_H-i-s');

    if (!copy($file_path, $backup_path)) {
      return [
        'success' => false,
        'backup' => null,
        'error' => 'Failed to create backup file',
      ];
    }
  }

  // ============================================
  // 3. GENERATE FILE CONTENT
  // ============================================
  $timestamp = date('Y-m-d H:i:s');

  // Use var_export to convert array to PHP code (preserves types!)
  $settings_export = var_export($settings, true);

  // Build file content
  $content = <<<PHP
  <?php
  // ============================================
  // NOVA CONFIGURATION VALUES
  // ============================================
  // DO NOT EDIT MANUALLY - Use Super Admin Settings Page
  // This file is automatically generated
  //
  // Last updated: {$timestamp}
  // Updated by: {$admin_email}
  // ============================================

  // Prevent multiple inclusions
  if (defined('NOVA_CONFIG_VALUES_LOADED')) {
      return;
  }
  define('NOVA_CONFIG_VALUES_LOADED', true);

  // Configuration array
  \$nova_settings = {$settings_export};

  // ============================================
  // END OF CONFIGURATION VALUES
  // ============================================
  ?>
  PHP;

  // ============================================
  // 4. WRITE FILE
  // ============================================
  $write_result = file_put_contents($file_path, $content);

  if ($write_result === false) {
    return [
      'success' => false,
      'backup' => $backup_path,
      'error' =>
        'Cannot write to nova_config_values.php. Check file permissions (chmod 777 on /nova/conf/ directory)',
    ];
  }

  // ============================================
  // 5. SET FILE PERMISSIONS
  // ============================================
  chmod($file_path, 0644); // rw-r--r-- (owner can write, others read-only)

  // ============================================
  // 6. SUCCESS
  // ============================================
  return [
    'success' => true,
    'backup' => $backup_path,
    'error' => null,
    'bytes_written' => $write_result,
  ];
}

// ============================================
// END OF SETTINGS WRITER
// ============================================

?>
